[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
color-eyre = "0.6.2"
derive_more = "0.99.17"
nom = "7.1.3"
rayon = "1.8.0"
strum = { version = "0.25.0", features = ["derive"] }
winnow = "0.5.25"
